// Generated by `pnpm docs:sync` from docs/guide/caveats.data.json. Do not edit.

export type Caveat = {
  id: string;
  title: string;
  short: string;
  /** Card copy for this page. `null` when the demo cannot show this entry. */
  demoBody: string | null;
  kind: 'defect' | 'by-design';
  demoCorpusCanTrigger: boolean;
};

/**
 * EVERY library caveat, unfiltered. The demo decides which of them apply to
 * its own corpus — see the filter in `visible-caveats.ts`, and the reasoning
 * beside it.
 */
export const CAVEATS: Caveat[] = [
  {
    id: 'long-lines',
    title: 'Inside a line longer than 64 KB, results are approximate',
    short:
      'Past a 64 KB line with no terminator, a longer match is lost and `^` can match at a window edge.',
    demoBody: null,
    kind: 'defect',
    demoCorpusCanTrigger: false,
  },
  {
    id: 'nul-byte',
    title: 'A file containing a NUL byte reports no match',
    short:
      'A NUL byte discards the block of lines containing it, even when the match came earlier.',
    demoBody:
      "ripgrep's binary detection quits on a NUL byte, and a boolean cannot distinguish “binary, not searched” from “no match”. Plain text — the intended use — is unaffected.",
    kind: 'defect',
    demoCorpusCanTrigger: true,
  },
  {
    id: 'crlf-dollar',
    title: '`$` does not match on CRLF files',
    short:
      'On Windows-authored text the `\\r` sits between your text and the anchor, so `needle$` misses what `needle` finds.',
    demoBody: null,
    kind: 'defect',
    demoCorpusCanTrigger: false,
  },
  {
    id: 'concurrent-dedup',
    title:
      'Concurrent searches of one URL are only de-duplicated when the cache is on',
    short:
      'With the cache off, two concurrent searches of one URL both download it — correct answers, wasted request.',
    demoBody: null,
    kind: 'defect',
    demoCorpusCanTrigger: false,
  },
  {
    id: 'no-ranking',
    title: 'No ranking',
    short:
      'No match counts, line numbers or relevance ordering — netgrep cannot sort files by how well they match.',
    demoBody:
      'netgrep answers whether a pattern occurs in a file and — if you ask — the first line it occurs on, with each match highlighted within it. It does not rank: no match counts, no line numbers, no relevance ordering, so it cannot sort these cards by how well they match. If you need that, a prebuilt index — Pagefind, Lunr, FlexSearch — is the right tool.',
    kind: 'by-design',
    demoCorpusCanTrigger: false,
  },
];
