/**
 * Post-processing for `wasm-pack build`.
 *
 * Three jobs, all of them load-bearing:
 *
 *  1. Mark the generated `pkg/` as ESM. wasm-pack does not emit
 *     `"type": "module"`, and without it Node treats `pkg/index.js` as
 *     CommonJS and the import fails.
 *
 *  2. Delete the `.gitignore` wasm-pack drops into `pkg/`. It contains `*`,
 *     and npm honours a package-internal .gitignore, which silently empties
 *     the published tarball. See the comment at the step itself.
 *
 *  3. Copy the version out of `Cargo.toml` into `packages/search/package.json`.
 *     Cargo.toml is the single source of truth for this package's version — the
 *     npm manifest is a hand-written wrapper around the wasm-pack output, so
 *     without this the two drift silently and a release ships the wrong number.
 *     See docs/BACKLOG.md item 9.
 */
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));
const writeJson = (path, value) =>
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);

// 1. `pkg/package.json` is regenerated by every build and consumed as ESM.
const generatedPath = join(packageRoot, 'pkg', 'package.json');
const generated = readJson(generatedPath);

generated.type = 'module';
writeJson(generatedPath, generated);

// 2. Delete the `.gitignore` wasm-pack drops into pkg/. It contains `*`, and
// npm honours a package-internal .gitignore when there is no .npmignore — so
// with `"files": ["pkg"]` in the wrapper manifest it silently excludes the
// entire directory and publishes a tarball containing no WASM at all.
//
// Nothing is lost: packages/search/.gitignore already ignores pkg/.
const generatedGitignore = join(packageRoot, 'pkg', '.gitignore');

if (existsSync(generatedGitignore)) {
  rmSync(generatedGitignore);
}

// 3. Cargo.toml -> package.json version sync.
const cargoToml = readFileSync(join(packageRoot, 'Cargo.toml'), 'utf8');
const cargoVersion = cargoToml.match(/^version\s*=\s*"([^"]+)"/m)?.[1];

if (!cargoVersion) {
  throw new Error('Could not read `version` from packages/search/Cargo.toml');
}

const manifestPath = join(packageRoot, 'package.json');
const manifest = readJson(manifestPath);

if (manifest.version !== cargoVersion) {
  console.warn(
    `post_build: syncing @netgrep/search ${manifest.version} -> ${cargoVersion} (from Cargo.toml)`,
  );

  manifest.version = cargoVersion;
  writeJson(manifestPath, manifest);
}
