/**
 * Renderers for the caveat data. Pure: they take the parsed array and return
 * strings. All file I/O lives in `scripts/docs-sync.mjs`.
 *
 * THESE ONLY EVER RENDER. Removing a caveat is a human deleting an entry from
 * `docs/guide/caveats.data.json` in the PR that fixes the defect — see
 * AGENTS.md §2.3, which asks that the list never be shortened to tidy a page.
 */

export const GENERATED_BY =
  'Generated by `pnpm docs:sync` from docs/guide/caveats.data.json. Do not edit.';

export const BEGIN = '<!-- BEGIN GENERATED CAVEATS -->';
export const END = '<!-- END GENERATED CAVEATS -->';

const DOCS_URL = 'https://netgrep.diegopasquali.com/docs/';
const BACKLOG_URL =
  'https://github.com/dgopsq/netgrep/blob/main/docs/BACKLOG.md';

/** `kind: 'defect'` first — a reader scanning for bugs should not wade past
 *  the things that are working as intended. */
const isDefect = (caveat) => caveat.kind === 'defect';

export function renderGuideSection(caveats) {
  const defects = caveats.filter(isDefect);
  const byDesign = caveats.filter((caveat) => !isDefect(caveat));

  const entry = (caveat) =>
    [
      // An explicit anchor, because the fragment has to be the caveat's `id`
      // and not a slug of its title. The README's generated bullets link to
      // `/docs/#<id>`, and a title is edited far more often than an id — "No
      // ranking" has already been retitled twice. GitHub renders a bare
      // anchor element invisibly, and markdown-it passes it through, so the
      // same fragment resolves on both surfaces.
      `<a id="${caveat.id}"></a>`,
      '',
      `### ${caveat.title}`,
      '',
      caveat.body,
      caveat.backlog
        ? `\nTracked as [BACKLOG ${caveat.backlog}](${BACKLOG_URL}#${caveat.backlog}), and pinned by a test.`
        : null,
    ]
      .filter((part) => part !== null)
      .join('\n');

  return [
    `<!-- ${GENERATED_BY} -->`,
    '',
    '# Limitations',
    '',
    'netgrep is experimental, and the following are real and **documented rather than fixed**.',
    'Each defect is pinned by a test, so it cannot change unnoticed.',
    '',
    '## Defects',
    '',
    defects.map(entry).join('\n\n'),
    '',
    '## By design',
    '',
    'These are not bugs and will not be fixed. They are what the shape of the answer costs.',
    '',
    byDesign.map(entry).join('\n\n'),
    '',
  ].join('\n');
}

export function renderReadmeList(caveats) {
  return caveats
    .filter(isDefect)
    .map(
      (caveat) =>
        `- **[${caveat.title}](${DOCS_URL}#${caveat.id})** — ${caveat.short}`,
    )
    .join('\n');
}

/** Single-quoted output, because Biome's `quoteStyle` is `single`. */
const quote = (value) =>
  `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

export function renderCaveatsModule(caveats) {
  const entries = caveats
    .map((caveat) =>
      [
        '  {',
        `    id: ${quote(caveat.id)},`,
        `    title: ${quote(caveat.title)},`,
        `    short: ${quote(caveat.short)},`,
        `    demoBody: ${caveat.demoBody === null ? 'null' : quote(caveat.demoBody)},`,
        `    kind: ${quote(caveat.kind)},`,
        `    demoCorpusCanTrigger: ${caveat.demoCorpusCanTrigger},`,
        '  },',
      ].join('\n'),
    )
    .join('\n');

  return `// ${GENERATED_BY}

export type Caveat = {
  id: string;
  title: string;
  short: string;
  /** Card copy for this page. \`null\` when the demo cannot show this entry. */
  demoBody: string | null;
  kind: 'defect' | 'by-design';
  demoCorpusCanTrigger: boolean;
};

/**
 * EVERY library caveat, unfiltered. The demo decides which of them apply to
 * its own corpus — see the filter in \`visible-caveats.ts\`, and the reasoning
 * beside it.
 */
export const CAVEATS: Caveat[] = [
${entries}
];
`;
}

/**
 * Splices `block` between the `BEGIN`/`END` markers in `readme`.
 *
 * `end < start` is checked too: with the markers swapped, the splice below
 * would happily produce a document with both markers duplicated and a
 * section repeated — corrupt output from a guard that thought it passed.
 */
export function spliceReadme(readme, block) {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);

  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README.md is missing or has misordered ${BEGIN} / ${END} markers. Restore them; the caveat list is generated.`,
    );
  }

  return `${readme.slice(0, start)}${BEGIN}\n${block}\n${readme.slice(end)}`;
}
