/**
 * Renderers for the caveat data. Pure: they take the parsed array and return
 * strings. All file I/O lives in `scripts/docs-sync.mjs`.
 *
 * THESE ONLY EVER RENDER. Removing a caveat is a human deleting an entry from
 * `docs/guide/caveats.data.json` in the PR that fixes the defect — see
 * AGENTS.md §2.3, which asks that the list never be shortened to tidy a page.
 */

export const GENERATED_BY =
  'Generated by `pnpm docs:sync` from docs/guide/caveats.data.json. Do not edit.';

export const BEGIN = '<!-- BEGIN GENERATED CAVEATS -->';
export const END = '<!-- END GENERATED CAVEATS -->';

const DOCS_URL = 'https://netgrep.diegopasquali.com/docs/';

/**
 * The data file's `backlog` field is deliberately read by nothing. It records
 * which item pins a defect, for whoever edits the file; published
 * documentation does not send a reader to an internal tracker. Keep it — it is
 * provenance, not dead weight.
 */

/** `kind: 'defect'` first — a reader scanning for bugs should not wade past
 *  the things that are working as intended. */
const isDefect = (caveat) => caveat.kind === 'defect';

export function renderGuideSection(caveats) {
  const defects = caveats.filter(isDefect);
  const byDesign = caveats.filter((caveat) => !isDefect(caveat));

  const entry = (caveat) =>
    [
      // An explicit anchor, because the fragment has to be the caveat's `id`
      // and not a slug of its title. The README's generated bullets link to
      // `/docs/#<id>`, and a title is edited far more often than an id — "No
      // ranking" has already been retitled twice. GitHub renders a bare
      // anchor element invisibly, and markdown-it passes it through, so the
      // same fragment resolves on both surfaces.
      `<a id="${caveat.id}"></a>`,
      '',
      `### ${caveat.title}`,
      '',
      caveat.body,
    ].join('\n');

  return [
    `<!-- ${GENERATED_BY} -->`,
    '',
    '# Limitations',
    '',
    'netgrep is experimental, and the following are documented rather than fixed.',
    'Each defect is pinned by a test, so it cannot change unnoticed.',
    '',
    '## Defects',
    '',
    defects.map(entry).join('\n\n'),
    '',
    '## By design',
    '',
    'These are not bugs and will not be fixed.',
    '',
    byDesign.map(entry).join('\n\n'),
    '',
  ].join('\n');
}

export function renderReadmeList(caveats) {
  return caveats
    .filter(isDefect)
    .map(
      (caveat) =>
        `- **[${caveat.title}](${DOCS_URL}#${caveat.id})** — ${caveat.short}`,
    )
    .join('\n');
}

/**
 * Splices `block` between the `BEGIN`/`END` markers in `readme`.
 *
 * `end < start` is checked too: with the markers swapped, the splice below
 * would happily produce a document with both markers duplicated and a
 * section repeated — corrupt output from a guard that thought it passed.
 */
export function spliceReadme(readme, block) {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);

  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README.md is missing or has misordered ${BEGIN} / ${END} markers. Restore them; the caveat list is generated.`,
    );
  }

  return `${readme.slice(0, start)}${BEGIN}\n${block}\n${readme.slice(end)}`;
}
