on: [push]

name: Main CI workflow

jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'
          cache: 'yarn'
      - run: yarn
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: yarn nx run-many --target=lint
      - run: yarn nx run-many --target=test
