on:
  push:
    tags:
      - search-**

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml

  publish:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'
          cache: 'yarn'
      - run: yarn
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: yarn nx build search
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          greater-version-only: true
          package: ./packages/search/pkg/package.json
