[package]
name = "search"
version = "0.1.4"
edition = "2021"
repository = "https://github.com/dgopsq/netgrep"
description = "The power of ripgrep over HTTP"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.82"
wee_alloc = "0.4.5"
grep = { git = "https://github.com/dgopsq/ripgrep", tag = "13.0.0-wasm" }

[dev-dependencies]
wasm-bindgen-test = "0.3.32"

[profile.release]
lto = true
opt-level = 's'